project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - index.qmd
    - C00_coding.qmd
    - C01_observations.qmd
    - C02_background.qmd
    - C03_covariates.qmd
    - C04_models.qmd
    - C05_prediction.qmd
    - S01_observations.qmd
    - about.qmd
execute: 
  cache: false

website:
  title: "Colby Forecasting 2025"
  page-navigation: true
  back-to-top-navigation: true
  page-footer: "Copyright 2025, Bigelow Laboratory for Ocean Science" 
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: Home
        href: index.qmd
      - text: Coding
        href: C00_coding.qmd
      - text: Observations
        href: C01_observations.qmd
      - text: Background
        href: C02_background.qmd
      - text: Covariates
        href: C03_covariates.qmd
      - text: Models
        href: C04_models.qmd
      - text: Prediction
        href: C05_prediction.qmd
      - text: My_observations
        href: S01_observations.qmd
      - text: About
        href: about.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/BigelowLab/ColbyForecasting2025
          - text: Report a bug or ask a question
            url:  https://github.com/BigelowLab/ColbyForecasting2025/issues
          - text: Wiki
            url:  https://github.com/BigelowLab/ColbyForecasting2025/wiki
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true

editor: source

